// This code was generated by `SqlHydra.SqlServer` -- v4.0.0.
namespace SqlHydraCorrelatedQueryTest

open SqlHydra
open SqlHydra.Query

module Version =
    let cli = System.Version(4, 0, 0)
    let ns = "SqlHydraCorrelatedQueryTest"
    SqlHydra.Query.VersionCheck.assertIsCompatible cli ns

module dbo =

    [<CLIMutable>]
    type CorrelatedQueryTestTable =
        { [<ProviderDbType("Int")>]
          field1: int
          [<ProviderDbType("Date")>]
          field2: System.DateOnly
          [<ProviderDbType("Float")>]
          field3: double
          [<ProviderDbType("DateTime2")>]
          timestamp: System.DateTime }

    let CorrelatedQueryTestTable = table<CorrelatedQueryTestTable>

module sys =

    [<CLIMutable>]
    type database_firewall_rules =
        { [<ProviderDbType("Int")>]
          id: int
          [<ProviderDbType("NVarChar")>]
          name: string
          [<ProviderDbType("VarChar")>]
          start_ip_address: string
          [<ProviderDbType("VarChar")>]
          end_ip_address: string
          [<ProviderDbType("DateTime")>]
          create_date: System.DateTime
          [<ProviderDbType("DateTime")>]
          modify_date: System.DateTime }

    let database_firewall_rules = table<database_firewall_rules>


type QueryContextFactory =
    { OpenContext: unit -> QueryContext
      OpenContextAsync: unit -> System.Threading.Tasks.Task<QueryContext> }

    interface IQueryContextFactory with
        member this.OpenContextAsync() = this.OpenContextAsync()

    static member Create(connectionString: string, ?sqlLogger) =
        let emitter = SqlHydra.Query.SqlServerEmitter()

        let createConn () : System.Data.Common.DbConnection =
            new Microsoft.Data.SqlClient.SqlConnection(connectionString)

        let openContext () =
            let conn = createConn ()
            conn.Open()
            let ctx = new QueryContext(conn, emitter)
            sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
            ctx

        let openContextAsync () =
            task {
                let conn = createConn ()
                do! conn.OpenAsync()
                let ctx = new QueryContext(conn, emitter)
                sqlLogger |> Option.iter (fun logger -> ctx.Logger <- logger)
                return ctx
            }

        { OpenContext = openContext
          OpenContextAsync = openContextAsync }
